/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema.escuela;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author angel
 */
public class PantallaRegistro extends javax.swing.JInternalFrame {

    /**
     * Creates new form PantallaRegistro
     */
    
    public PantallaRegistro() {
        
        initComponents ();
        
        Connection con;
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PantallaRegistro.class.getName()).log(Level.SEVERE, null, ex);
        }
        

        
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        tfApellido = new javax.swing.JTextField();
        tfNombre = new javax.swing.JTextField();
        tfApellidoM = new javax.swing.JTextField();
        dcEdad = new javax.swing.JTextField();
        rbSistemas = new javax.swing.JRadioButton();
        rbCivil = new javax.swing.JRadioButton();
        rbGestion = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("Registro de Alumnos");

        tfApellido.setText("Ingrese el apellido paterno");
        tfApellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfApellidoFocusGained(evt);
            }
        });
        tfApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfApellidoActionPerformed(evt);
            }
        });

        tfNombre.setText("Ingrese el nombre");
        tfNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfNombreFocusGained(evt);
            }
        });
        tfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNombreActionPerformed(evt);
            }
        });

        tfApellidoM.setText("Ingrese el apellido materno");
        tfApellidoM.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfApellidoMFocusGained(evt);
            }
        });
        tfApellidoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfApellidoMActionPerformed(evt);
            }
        });

        dcEdad.setText("Ingrese la edad");
        dcEdad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dcEdadFocusGained(evt);
            }
        });
        dcEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dcEdadActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbSistemas);
        rbSistemas.setText("Sistemas");
        rbSistemas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSistemasActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbCivil);
        rbCivil.setText("Civil");
        rbCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCivilActionPerformed(evt);
            }
        });

        buttonGroup3.add(rbGestion);
        rbGestion.setText("Gestion");

        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(tfApellidoM, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfApellido, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(dcEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(rbSistemas)
                                .addGap(77, 77, 77)
                                .addComponent(rbCivil)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                                .addComponent(rbGestion))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dcEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbSistemas)
                            .addComponent(rbCivil)
                            .addComponent(rbGestion))
                        .addGap(16, 16, 16)))
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfApellidoActionPerformed

    private void tfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNombreActionPerformed

    private void tfApellidoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfApellidoMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfApellidoMActionPerformed

    private void dcEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dcEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dcEdadActionPerformed

    private void rbCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCivilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbCivilActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        JTextField edad = dcEdad;
        
        String carrera = "";
        if(rbSistemas.isSelected()){
            carrera = "Sistemas";
        }if (rbCivil.isSelected()){
            carrera = "Civil";
        }if(rbGestion.isSelected()){
            carrera = "Gestion";
        }
                
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/sistemaescuela","root", "");
            Statement stmt = con.createStatement();
            stmt.executeUpdate("INSERT INTO alumnos VALUES('"+tfNombre.getText()+"','"+tfApellido.getText()+"','"+tfApellidoM.getText()+"','"+dcEdad.getText()+"','"+carrera+"')");
        } catch (SQLException ex) {
            Logger.getLogger(PantallaRegistro.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"No se puede conectar con la base de datos");
        }
        JOptionPane.showMessageDialog(null, "El alumno ha sido registrado exitosamente");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rbSistemasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSistemasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbSistemasActionPerformed

    private void tfNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNombreFocusGained
        // TODO add your handling code here:
        tfNombre.setText("");
    }//GEN-LAST:event_tfNombreFocusGained

    private void tfApellidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfApellidoFocusGained
        // TODO add your handling code here:
        tfApellido.setText("");
    }//GEN-LAST:event_tfApellidoFocusGained

    private void tfApellidoMFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfApellidoMFocusGained
        // TODO add your handling code here:
        tfApellidoM.setText("");
    }//GEN-LAST:event_tfApellidoMFocusGained

    private void dcEdadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dcEdadFocusGained
        // TODO add your handling code here:
        dcEdad.setText("");
    }//GEN-LAST:event_dcEdadFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JTextField dcEdad;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton rbCivil;
    private javax.swing.JRadioButton rbGestion;
    private javax.swing.JRadioButton rbSistemas;
    private javax.swing.JTextField tfApellido;
    private javax.swing.JTextField tfApellidoM;
    private javax.swing.JTextField tfNombre;
    // End of variables declaration//GEN-END:variables
}
